name: '"Render AWS Batch Job Definition" Action for GitHub Actions'
description: "Inserts a container image URI into an Amazon Batch job definition JSON file, creating a new file."
branding:
  icon: "cloud"
  color: "green"
inputs:
  job-definition:
    description: "The path to the Batch job definition JSON file"
    required: true
  image:
    description: "The URI of the container image to insert into the Batch job definition"
    required: true
outputs:
  job-definition:
    description: "The path to the rendered task definition file"
runs:
  using: "node16"
  main: "dist/index.js"
