name: 'Amazon Batch "Render Job Definition" Action for GitHub Actions'
description: "Inserts a container image URI into a an Amazon Batch job definition JSON file, creating a new file."
branding:
  icon: "cloud"
  color: "orange"
inputs:
  job-definition:
    description: "The path to the Batch job definition JSON file"
    required: true
  image:
    description: "The URI of the container image to insert into the Batch job definition"
    required: true
outputs:
  task-definition:
    description: "The path to the rendered task definition file"
runs:
  using: "node12"
  main: "dist/index.js"
